---
title: "Pre-processing"
output: html_document
---

# Pre-processing to combine years of flights data

```{r}
library(tidyverse)
library(readr)
library(readxl)
```

```{r}
parse_table <- function(fileName) { 
                read_csv( file.path("data", fileName, fsep = "/")
                        , col_select = c( "OP_CARRIER"
                                        , "ORIGIN"
                                        , "DEST"
                                        , "CRS_DEP_TIME"
                                        , "ARR_DELAY"
                                        , "CANCELLED"
                                        , "CARRIER_DELAY"
                                        , "WEATHER_DELAY"
                                        , "NAS_DELAY"
                                        , "SECURITY_DELAY"
                                        , "LATE_AIRCRAFT_DELAY"
                                        )
                        , col_types = cols(OP_CARRIER = col_factor(levels = c( "9E"
                                                                             , "AA"
                                                                             , "MQ"
                                                                             , "G4"
                                                                             , "OH"
                                                                             , "B6"
                                                                             , "YV"
                                                                             , "EV"
                                                                             , "F9"
                                                                             , "YX"
                                                                             , "HA"
                                                                             , "NK"
                                                                             , "UA"
                                                                             , "OO"
                                                                             , "WN"
                                                                             , "AS"
                                                                             , "DL"
                                                                             )
                                                                   )
                                           )
                        )
}
```

```{r}
flights <- parse_table("2018.csv")

saveRDS(flights, file = "data/flights.rds")
```

# Carrier performance tables

```{r}
delay.types <- data.frame( OP_CARRIER = unique(flights$OP_CARRIER) )


delay.types$CARRIER_DELAY <- sapply(delay.types$OP_CARRIER, function(x) {
                                                              d <- flights[flights$OP_CARRIER == x, ] %>% select(1, 7)
                                                              d <- d[d$CARRIER_DELAY > 0, ]
                                                              d[!is.na(d$CARRIER_DELAY), ] %>% nrow()  
                                                            }
                                   )

delay.types$WEATHER_DELAY <- sapply(delay.types$OP_CARRIER, function(x) {
                                                              d <- flights[flights$OP_CARRIER == x, ] %>% select(1, 8)
                                                              d <- d[d$WEATHER_DELAY > 0, ]
                                                              d[!is.na(d$WEATHER_DELAY), ] %>% nrow()  
                                                            }
                                   )

delay.types$NAS_DELAY <- sapply(delay.types$OP_CARRIER, function(x) {
                                                          d <- flights[flights$OP_CARRIER == x, ] %>% select(1, 9)
                                                          d <- d[d$NAS_DELAY > 0, ]
                                                          d[!is.na(d$NAS_DELAY), ] %>% nrow()  
                                                        }
                               )

delay.types$SECURITY_DELAY <- sapply(delay.types$OP_CARRIER, function(x) {
                                                              d <- flights[flights$OP_CARRIER == x, ] %>% select(1, 10)
                                                              d <- d[d$SECURITY_DELAY > 0, ]
                                                              d[!is.na(d$SECURITY_DELAY), ] %>% nrow()  
                                                             }
                                    )

delay.types$LATE_AIRCRAFT_DELAY <- sapply(delay.types$OP_CARRIER, function(x) {
                                                                   d <- flights[flights$OP_CARRIER == x, ] %>% select(1, 11)
                                                                   d <- d[d$LATE_AIRCRAFT_DELAY > 0, ]
                                                                   d[!is.na(d$LATE_AIRCRAFT_DELAY), ] %>% nrow()   
                                                                  }
                                         )

delay.types <- delay.types[-13,]
saveRDS(delay.types, file = "data/delay_types.rds")
```

# Cleaning the Review table

```{r}
library(readr)
uscities <- read_csv('data/uscities.csv')
colnames(airports)[colnames(airports) == "LATITUDE"] <- "AIRPORT LATITUDE"
colnames(airports)[colnames(airports) == "LONGITUDE"] <- "AIRPORT LONGITUDE"
uscities_sub <- uscities[, c("city", "lat", "lng")]
merged_data <- merge(airports, uscities_sub, by.x="city", by.y = "city", all.x=TRUE)
uscities_sub <- uscities[, c("city", "lat", "lng")]
merged_data <- merge(airports, uscities_sub, by.x="CITY", by.y = "city", all.x=TRUE)

duplicateRows <- duplicated(airports$CITY)
merged_data <- merge(airports, uscities_sub, by.x="CITY", by.y = "city")

uscities_sub <- uscities[, c("city", "state_id", "lat", "lng")]

uscities_sub <- uscities[, c("city", "state_id", "lat", "lng")]
merged_data <- merge(airports, uscities_sub, by.x=c("CITY", "STATE"), by.y=c("city", "state_id"))
duplicateRows <- duplicated(airports$CITY)
merged_data <- merge(airports, uscities_sub, by.x="CITY", by.y = "city")

uscities_sub <- uscities[, c("city", "state_id", "lat", "lng")]

uscities_sub <- uscities[, c("city", "state_id", "lat", "lng")]
merged_data <- merge(airports, uscities_sub, by.x=c("CITY", "STATE"), by.y=c("city", "state_id"))
```


```{r}
library(tidyverse)
airports_merged <- merged_data %>%
  mutate(Location = paste0(merged_data$AIRPORT, 
                           ' (', merged_data$IATA, ')'))
saveRDS(merged_data, file = 'data/airports.rds')
airports_merged = airports_merged %>% rename('LOCATION' = 'Location')
saveRDS(airports_merged, file = 'data/airports-merged.rds')

reviews <- read_excel("data/capstone_airline_reviews3.xlsx")
```

```{r}
reviews <- reviews[1:2]
reviews <- reviews[!is.na(reviews$airline), ]

saveRDS(reviews, file = "data/reviews.rds")
```

```{r}
arr_delays <- flights %>% select(1,5)
for (x in (unique(arr_delays$OP_CARRIER))) {
  arr_delays %>%
      filter(OP_CARRIER == x) %>%
      saveRDS(file = paste0('data/', x, '.rds'))
}
```

```{r}
predictor <- flights %>% select(1:6)
for (x in (unique(predictor$OP_CARRIER))) {
  predictor %>%
      filter(OP_CARRIER == x) %>%
      select(2:6) %>%
      saveRDS(file = paste0('data/', x, '_full.rds'))
}
```

```{r}
aircrafts <- read_excel("data/FAA-Aircraft-Char-DB-AC-150-5300-13B-App-2023-09-07.xlsx")
saveRDS(aircrafts, file = "data/aircrafts.rds")
```
```{r}
tidied_reviews <- reviews %>%
  rename(OP_CARRIERS = 'airline', REVIEWS = 'overall') %>%
  mutate(OP_CARRIERS = case_when(
    OP_CARRIERS == "Spirit Airlines" ~ "NK",
    OP_CARRIERS == "American Airlines" ~ 'AA',
    OP_CARRIERS == 'Delta Air Lines' ~ 'DL',
    OP_CARRIERS == 'United Airlines' ~ 'UA',
    OP_CARRIERS == 'Alaska Airlines' ~ 'AS',
    OP_CARRIERS == 'Jetblue Airways' ~ 'B6',
    OP_CARRIERS == 'Frontier Airlines' ~ 'F9',
    OP_CARRIERS == 'Southwest Airlines' ~ 'WN'))

tidied_reviews <- tidied_reviews %>%
  filter(OP_CARRIERS %in% c('NK',
                            'WN',
                            'AA',
                            'DL',
                            'UA',
                            'AS',
                            'B6',
                            'F9'))

#endeavor airlines doesn't exist on table (9E)
#atlantic southeast (EV)
#allegiant air (G4)
#Hawaiian air (HA)
#american eagle (MQ)
#comair (OH)
#skywest (OO)
#Mesa (YV)
#Midwest (YX)


airplane_crashes <- d %>%
    rename(OP_CARRIER = 'Aircaft_Operator', FLIGHT_TYPE = 'Aircaft_Nature', INCIDENT_TYPE = 'Incident_Category') %>%
    mutate(OP_CARRIER = case_when(
        OP_CARRIER == 'Delta Air Lines' ~ 'DL',
        OP_CARRIER =='American Airlines' ~ 'AA',
        OP_CARRIER =='Spirit Airlines' ~ 'NK',
        OP_CARRIER =='United Airlines' ~ 'UA',
        OP_CARRIER =='Alaska Airlines' ~ 'AS',
        OP_CARRIER == 'JetBlue Airways' ~ 'B6',
        OP_CARRIER == 'Frontier Airlines' ~ 'F9',
        OP_CARRIER == 'Southwest Airlines' ~ 'WN',
        OP_CARRIER == 'Allegiant Air' ~ 'G4',
        OP_CARRIER == 'Endeavor Air' ~ '9E',
        OP_CARRIER == 'Southeast Airlines' ~ 'EV',
        OP_CARRIER == 'Hawaiian Airlines' ~ 'HA',
        OP_CARRIER == 'American Eagle Airlines' ~ 'MQ',
        OP_CARRIER == 'Comair' ~ 'OH',
        OP_CARRIER == 'SkyWest Airlines' ~ 'OO',
        OP_CARRIER == 'Mesa Airlines' ~ 'YV',
        OP_CARRIER == 'Mesa Airlines, op.for United Express' ~ 'YV',
        OP_CARRIER == 'Mesa Airlines, opf US Airways' ~ 'YV',
        OP_CARRIER == 'Air Midwest, op.for US Airways Express' ~ 'YX')) 

airplane_crashes <- airplane_crashes %>%
    filter(OP_CARRIER %in% c('NK', 'WN', 'AA', 'DL', 'UA', 'AS', 'B6', 'F9', 'YX', 'YV', 'OO', 'OH', 'MQ', 'HA', 'G4', 'EV', '9E'))

airplane_crashes <- airplane_crashes %>%
    select(Incident_Date, Aircaft_Model, OP_CARRIER, FLIGHT_TYPE, INCIDENT_TYPE, Incident_Location, `Incident_Cause(es)`) %>%
    rename(DATE = 'Incident_Date', AIRCRAFT = 'Aircaft_Model', LOCATION = 'Incident_Location', CAUSE = 'Incident_Cause(es)')

```

```{r}
carriers_list <- c( "Endeavor Air" = "9E"
                  , "American Airlines" = "AA"
                  , "Envoy Air" = "MQ"
                  , "Allegiant Air" = "G4"
                  , "Jetstream Intl" = "OH"
                  , "Jetblue Airways" = "B6"
                  , "Mesa Airlines" = "YV"
                  , "ExpressJet Airlines" = "EV"
                  , "Frontier Airlines" = "F9"
                  , "Republic Airlines" = "YX"
                  , "Hawaiian Airlines" = "HA"
                  , "Spirit Airlines" = "NK"
                  , "United Airlines" = "UA"
                  , "Skywest Airlines" = "OO"
                  , "Southwest Airlines" = "WN"
                  , "Alaska Airlines" = "AS"
                  , "Delta Air Lines" = "DL"
                  )

saveRDS(carriers_list, "data/carriers.rds")
```

